/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.15
 * Generated at: 2023-11-10 23:11:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1699571251392L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1699657916163L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1699571251398L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- link css -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"modelo.css\">\r\n");
      out.write("\r\n");
      out.write("    <title>TryBank</title>\r\n");
      out.write("    ");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/bootstrap.min.css\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"princ\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"marge\" class=\"container-fluid\">\r\n");
      out.write("<nav id=\"navegacao\" class=\"navbar navbar-expand-lg \">\r\n");
      out.write("\r\n");
      out.write("<!--inicio logo -->\r\n");
      out.write("      <a id=\"logo\" class=\"navbar-brand\" href=\"#\">TryBank</a>\r\n");
      out.write("<!-- Fim da logo   -->  \r\n");
      out.write("      \r\n");
      out.write("<!-- inicio Nav -->\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarTogglerDemo01\" aria-controls=\"navbarTogglerDemo01\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarTogglerDemo01\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("       \r\n");
      out.write("      </ul>\r\n");
      out.write("      <div  class=\"d-flex\">\r\n");
      out.write("        <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Inicio</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Login</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"btn btn-success\" href=\"cadastro.jsp\">Cadastro</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("  </div>\r\n");
      out.write("<!-- fim da Nave -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    \r\n");
      out.write("    <h1 class=\"text-center\" style=\"margin-top: 12px;\" >Bem Vindo</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <h5 class=\"text-center\" style=\"margin-top: 24px; margin-bottom: 20px;\">\r\n");
      out.write("    \r\n");
      out.write("      Bem-vindo ao Tribank, sua solução inovadora para transformar sua vida financeira.\r\n");
      out.write("      Como uma fintech dedicada, nosso objetivo é simplificar e otimizar sua experiência financeira, oferecendo serviços inteligentes e acessíveis.\r\n");
      out.write("    \r\n");
      out.write("    </h5>\r\n");
      out.write("    \r\n");
      out.write("    <p class=\"text-center\">\r\n");
      out.write("        <img src=\"./img/Taunb.png\" class=\"img-fluid img-thumbnail\" style=\"margin-top: 22px;\">\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\" >\r\n");
      out.write("\r\n");
      out.write("      	<h5 style=\"margin-top: 22px; \">Visão Geral</h5>\r\n");
      out.write("      	\r\n");
      out.write("      <p> \r\n");
      out.write("      \r\n");
      out.write("      Nossa missão é capacitar as pessoas a alcançarem seus objetivos financeiros de maneira fácil e eficiente,\r\n");
      out.write("      tornando a gestão financeira pessoal intuitiva e acessível.\r\n");
      out.write("      \r\n");
      out.write("      </p>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		<h5 class=\"recurso\" style=\"margin-top: 22px; border: 2px solid #00ff00; padding: 5px;\">Recursos Principais</h5>\r\n");
      out.write("\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li style=\"margin-top: 8px;\"><strong>Orçamento Inteligente:</strong> Atribuímos categorias automaticamente às suas despesas, proporcionando uma visão clara dos seus gastos.</li>\r\n");
      out.write("        <li style=\"margin-top: 8px;\"><strong>Investimentos Simplificados:</strong> Acesse oportunidades de investimento personalizadas, com informações claras e sugestões alinhadas aos seus objetivos.</li>\r\n");
      out.write("        <li style=\"margin-top: 8px;\"><strong>Transparência nas Transações:</strong> Detalhes claros sobre cada transação, ajudando você a entender melhor seus hábitos de gastos.</li>\r\n");
      out.write("        <li style=\"margin-top: 8px;\"><strong>Alertas Personalizados:</strong> Receba alertas inteligentes sobre datas de vencimento, movimentações suspeitas e oportunidades de economia.</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- cards propagandas  -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" style=\"margin-top: 12px; margin-bottom: 24px;\">\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-sm-12 col-md-6 col-lg-4 col-xl-3\"style= \"margin-bottom: 24px\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"./img/adas.png\" class=\"card-img-top\" alt=\"...\" style=\"width: 100%; height: 200px;\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">Adas</h5>\r\n");
      out.write("                    <p class=\"card-text\">Na ADAS, acreditamos que a educação financeira é a chave para construir um futuro financeiramente sólido.</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-primary\">Ver mais</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-sm-12 col-md-6 col-lg-4 col-xl-3\"style= \"margin-bottom: 24px\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"./img/selso.png\" class=\"card-img-top\" alt=\"...\" style=\"width: 100%; height: 200px;\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">FinanZero</h5>\r\n");
      out.write("                    <p class=\"card-text\">Na FinanZero, acreditamos em simplificar o processo de empréstimo, proporcionando taxas competitivas e condições flexíveis de pagamento.</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-primary\">Ver mais</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-sm-12 col-md-6 col-lg-4 col-xl-3\"style= \"margin-bottom: 24px\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"./img/vidas.png\" class=\"card-img-top\" alt=\"...\" style=\"width: 100%; height: 200px;\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">Vidas</h5>\r\n");
      out.write("                    <p class=\"card-text\">Na Vidas, entendemos que a vida é cheia de surpresas, e é por isso que fornecemos um suporte financeiro rápido e transparente.</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-primary\">Ver mais</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-sm-12 col-md-6 col-lg-4 col-xl-3\"style= \"margin-bottom: 24px\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"./img/Bilionary.png\" class=\"card-img-top\" alt=\"...\" style=\"width: 100%; height: 200px;\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">Bilionary</h5>\r\n");
      out.write("                    <p class=\"card-text\">Oferecemos uma combinação única de recursos avançados, análises especializadas e oportunidades de investimento exclusivas. </p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-primary\">Ver mais</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-12 col-md-6 col-lg-4 col-xl-3\"style= \"margin-bottom: 24px\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"./img/ECOnomise.png\" class=\"card-img-top\" alt=\"...\" style=\"width: 100%; height: 200px;\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">ECOnomise</h5>\r\n");
      out.write("                    <p class=\"card-text\">Na ECOnomise, proporcionamos empréstimos acessíveis com condições flexíveis, adaptadas às suas necessidades.</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-primary\">Ver mais</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-12 col-md-6 col-lg-4 col-xl-3\"style= \"margin-bottom: 24px\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"./img/Financas.png\" class=\"card-img-top\" alt=\"...\" style=\"width: 100%; height: 200px;\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">Finanças</h5>\r\n");
      out.write("                    <p class=\"card-text\">Aqui, transformamos conceitos complexos em lições acessíveis, capacitando você a tomar decisões inteligentes com seu dinheiro.</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-primary\">Ver mais</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-12 col-md-6 col-lg-4 col-xl-3\"style= \"margin-bottom: 24px\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"./img/tecnologia.jpg\" class=\"card-img-top\" alt=\"...\" style=\"width: 100%; height: 200px;\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">TecnoEmpreende</h5>\r\n");
      out.write("                    <p class=\"card-text\">Nossa abordagem combina conhecimentos tradicionais de negócios com as últimas inovações tecnológicas.</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-primary\">Ver mais</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-12 col-md-6 col-lg-4 col-xl-3\"style= \"margin-bottom: 24px\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img src=\"./img/Sifra.png\" class=\"card-img-top\" alt=\"...\" style=\"width: 100%; height: 200px;\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">Sifra</h5>\r\n");
      out.write("                    <p class=\"card-text\">Nossa escola adota uma abordagem inovadora, integrando tecnologia e experiências práticas para criar uma jornada educacional envolvente.</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-primary\">Ver mais</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/bootstrap.min.js\"></script>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
